name: Build C# Application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # تم التحديث إلى v4
    - uses: actions/checkout@v4

    # تم التحديث إلى v4
    - name: Unzip Project Files
      run: |
        if (Test-Path *.zip) {
          Expand-Archive -Path *.zip -DestinationPath "./Project_extracted" -Force
        }

    # تم التحديث إلى v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish Build
      run: |
        if (Test-Path "./Project_extracted") {
          dotnet publish "./Project_extracted" -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true
        } else {
          dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishReadyToRun=true
        }

    # تم التحديث إلى v4 ليتوافق مع السيرفرات الحالية
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyCSharpAppExecutable
        path: "**/bin/Release/**/publish/"
